FrEDI/R/utils_sv.R
createSystemData/2_configure_FrEDI_SV.Rmd
createSystemData/R/createSVData.R
createSystemData/R/update_sysdata.R
createSystemData/R/utils_configure_sv.R

Updated special cases for "Air Quality" (weights in "calc_tractImpacts")

Aq premature mortality2

---

FrEDI/R/run_fredi_sv.R
FrEDI/R/utils_sv.R
createSystemData/2_configure_FrEDI_SV.Rmd

patching a couple of errors for calculating SV impacts for SLR sectors

Edits to run_fredi_sv and utils_sv

---

createSystemData/R/createSystemData.R
createSystemData/R/loadData.R
createSystemData/R/test_loadData.R

Initial framework for testing input data transformations that occur during createsystemdata

Test dev createsystemsdata

---

createSystemData/1_configure_FrEDI_main.Rmd
createSystemData/R/configTests.R
createSystemData/R/configTests_utils.R
createSystemData/R/createSystemData.R
createSystemData/R/loadData.R
createSystemData/R/reshapeData.R

@knoiva-indecon Let me know if any of this doesn't make any sense. Tried to leave some notes on things where I know things need to be improved.

Draft new sector tests

---

createSystemData/1_configure_FrEDI_main.Rmd
createSystemData/R/configTests.R

Still a few things I'd like to discuss, especially on the plots

Fixes to testing workflow for new config tests

---

createSystemData/1_configure_FrEDI_main.Rmd
createSystemData/R/configTests_utils.R
createSystemData/R/outputTests.R

Initial general test for run_fredi output. Part of issue #51

Add initial run_fredi test

---

.github/workflows/test_fredi.yml
FrEDI/R/configTests.R
FrEDI/R/configTests_utils.R

Additions to test_fredi_yml and functions necessary to run test suite

Working test_fredi.yml

---

.github/workflows/test_fredi.yml

change logical in figure area

---

.github/workflows/test_fredi.yml
FrEDI/data_tests/report_figures/LICENSE

Fixed small issue with maintenance: tempInput is a data frame, not a function call (line 304 run_fredi)

Fix maintenance

---

FrEDI/R/testing_general_fredi_test.R
FrEDI/R/utils.R

in the get econ scalars function, we need to use year instead of year0 for joining. It was creating duplicate value issues.

Fix to duplicate values in scalars issue

---

FrEDI/R/import_inputs.R
FrEDI/R/run_fredi.R
FrEDI/R/utils_import_inputs.R

State-level updates for the import_impacts function

State level updates wm

---

FrEDI/R/aggregate_impacts.R

When aggregating to National Totals, we were grouping by a varying "state_pop" and "physicalmeasure" per sector, so we were getting multiple annual impacts at the National level per sector.

A few updates to aggregate_impacts.R

---

FrEDI/R/run_fredi_sv.R
FrEDI/R/utils_sv.R

Although the SV code did not change for the state level, the state level FrEDI code reorganized some list objects in `rDataList`. The SV functions use some `rDataList` objects. Required an update to the call for the list objects

SV state level initial fix hme

---

FrEDI/R/utils_create_report_figures.R
FrEDI/R/utils_plot_DOW_byImpactTypes.R
FrEDI/R/utils_plot_DOW_bySector.R
FrEDI/scripts/create_DoW_results.R

State level initial fix figures kmn

---

FrEDI/R/import_inputs.R
FrEDI/R/run_fredi.R
FrEDI/R/utils.R

Not ready for merging. Proposed changes

State level initial thru2300

---

.github/workflows/update_base_data.yml
FrEDI/R/run_fredi_sv.R
FrEDI/R/utils_sv.R

Adding merges and changes from thru2300 to state_level_initial

State level initial merge2300

---

FrEDI/R/run_fredi.R
FrEDI/R/utils.R

Modified some lines in utils to make sure that results are filtered to appropriate max year. Edited FrEDI to do the same. Also changed some messaging

Improved messaging

---

FrEDI/install/00_install.R
FrEDI/testing/utils_create_report_figures.R
FrEDI/testing/utils_plot_DOW_byImpactType.R
FrEDI/testing/utils_plot_DOW_byImpactTypes.R
FrEDI/testing/utils_plot_DOW_byModelType.R
FrEDI/testing/utils_plot_DOW_bySector.R
FrEDI/testing/utils_save_report_objects.R

Updated plots with a dashed line. Also updated plots with color-blind friendlier palettes. And adjusted the plot spacing

State level add sectors dashedline

---

FrEDI/R/run_fredi.R

Updating with GDP input fix

---

FrEDI/R/aggregate_impacts.R
FrEDI/R/import_inputs.R
FrEDI/R/run_fredi.R
FrEDI/R/utils_import_inputs.R

Merge pop scaling data, code edits

Merge pop scaling data, code edits

---

FrEDI/R/run_fredi_sv.R
FrEDI/R/utils_sv.R

Converted SV results back to the region level, since outputs may not be as accurate as small spatial resolutions.

Changed SV outputs back to region level

---

FrEDI/R/utils_import_inputs.R

Improved messaging on population columns

Pop downscaling message fix

---

FrEDI/R/utils_sv.R

Fixed issue with weight columns in FrEDI SV

Fix issue with weight column in SV

---

FrEDI/testing/utils_create_report_figures.R

Previously, was filtering to includeaggregate==1

Edited line in figures to filter to includeaggregate>=1

---

FrEDI/R/run_fredi_methane.R

Fix issue with `run_fredi_methane` when providing NOx emissions scenario only

Fix Issue #195

---

testing/utils_create_report_figures.R
testing/utils_plot_DOW_byModelType.R
testing/utils_report_figures_format_sector_names.R
testing/utils_report_figures_scales.R

Added fixes to:
* Change some for loop iterations to map
* Changed list labels
* Corrected function that calculates the number of rows in the plot grid from the number of columns
* Changed the x label expression to just text
* Edited the function formatting sector names to put extra spaces before the sector

Additional fixes for report figures

---

.github/workflows/2b_run_compare_tests.yml

Adding just the 2b action comparison test

just add 2b compare action

---

.github/workflows/2b_run_compare_tests.yml
testing/fredi_run_comparison_dashboard.rmd

Pulling in my 2baction into the New Sector branch so we can test with New Sector Data

Fredi actions 2b into new sector branch

---

.github/workflows/2b_run_compare_tests.yml
R/run_fredi.R
testing/fredi_run_comparison_dashboard.rmd

Solves #215 .
After inputsList data has been properly modified for the run, this adds the scenario data to the returnList scenario list if the option to return outputs as a list is true.

Bug Fix: Add input scenario to returnobject if option is set

---

R/aggregate_impacts.R
R/get_sectorInfo.R
R/run_fredi.R
R/run_fredi_sv.R
R/temps2slr.R
R/utils.R
R/utils_aggImpacts.R
R/utils_import_inputs.R
R/utils_sv.R
scripts/create_sector_maps.R
testing/utils_create_maps.R
testing/utils_otherReportFigs.R

Edits necessary to integrate the new data organization. Will make comments in the code comparison.

Edits to reorganization of Data flow

---

R/run_fredi.R

add dbDisconnect() to run_fredi()

---

R/run_fredi_ghg.R
man/run_fredi_ghg.Rd

update and roxygenize run_fredi_ghg documentation
